# /etc/rancher/k3s/config.yaml.d/kubeconfig.yaml
#
# everyone in the `wheel` group can use the cluster
# write config to /run, not to /etc
#
write-kubeconfig: /run/k3s.yaml
write-kubeconfig-mode: "0640"
write-kubeconfig-group: wheel
